name: "Danger Swift"
on: [pull_request]
jobs:
  build:
runs-on: macos-latest

steps:
- uses: actions/checkout@v2
- name: Build
run: xcodebuild -target "Danger test"

- name: Danger
run: danger-swift ci
env: ${{ secrets.BOT.KEY }}


